version: "3.8"

services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    volumes:
      - ./scripts:/scripts
    command: -jar DynamoDBLocal.jar -inMemory -sharedDb

  api:
    build:
      context: ./api
    ports:
      - "8081:8081"
    env_file:
      - ./api/.env
    command: >
      sh -c "/app/scripts/wait-for-it.sh dynamodb:8000 -- node /app/scripts/createUserScoresTable.js && npm start"

  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - ./frontend/.env
  #   command: >
  #     sh -c "/app/scripts/wait-for-it.sh localhost:8081 -- npm start"

networks:
  default:
    driver: bridge
