name: Deploy API

on:
  push:
    branches:
      - main
    paths:
      - "api/**"

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install API dependencies
        run: |
          cd api
          npm install

      - name: Run Tests
        run: |
          cd api
          npm run test

      - name: Build API
        run: |
          cd api
          npm run build

      - name: Deploy API
        run: |
          cd api
          sam deploy \
            --stack-name btc-price-guess-api \
            --no-confirm-changeset \
            --parameter-overrides \
              NodeEnv=${{ vars.NODE_ENV }} \
              DynamoDbEndpoint=${{ secrets.DYNAMODB_ENDPOINT }}
